!"Scorched Rusalka"
OR !"Sparkmage Apprentice"
OR !"Bloodscale Prowler"
OR !"Indentured Oaf"
OR !"Dryad Sophisticate"
OR !"Gatherer of Graces"
OR !"Gruul Scrapper"
OR !"Dowsing Shaman"
OR !"Bramble Elemental"
OR !"Gruul Nodorog"
OR !"Battering Wurm"
OR !"Scab-Clan Mauler"
OR !"Burning-Tree Bloodscale"
OR !"Streetbreaker Wurm"
OR !"Skarrgan Skybreaker"
OR !"Borborygmos"
OR !"Wild Cantor"
OR !"Gruul Guildmage"
OR !"Wildsize"
OR !"Fencer's Magemark"
OR !"Fists of Ironwood"
OR !"Beastmaster's Magemark"
OR !"Wurmweaver Coil"
OR !"Mountain"
OR !"Forest"
OR !"Skarrg, the Rage Pits"